### ISSUE TITLE
Missing the requirements.txt file

### ISSUE THREAD

**Issue by john-kruebbe-dxc** [DennizSvens/azure-voice-assistant#1]
Deniz:

I like your repo and would like to have the requriements.txt file.  Would you please add it to the repo?

I am using the following parameters:

Azure OpenAI GPT-4
Model - gpt-4-32k

Deployment Name - gpt-4-32k

Version - 0613

**Comment by DennizSvens** [comment]
Hi @john-kruebbe-dxc,

I've added requirements.txt now!
